#!/bin/bash

set -x

SETG=no
if [ "$1" = '-g' ] ; then
    SETG=yes
    shift
fi

GROUP=sw
if [ "$1" = '-G' ] ; then
    shift
    GROUP=$1
    shift
fi

args=("$@")
for arg in ${args[@]} ; do
    chgrp -hR $GROUP "$arg"
    chmod -R u+rwX,g+rwX,o+rX-w "$arg"
    [[ "$SETG" = 'no' ]] || find "$arg" -type d -exec chmod g+s {} \;
done



