mirror_dir: /sw/apps/mc3/latest/rackham/condamirror/bioconda
platforms:
  - linux-64
  - noarch
python_versions:
  - 2.7
  - 3.6
dest_channel:
  - local_repo_bioconda
dest_site:
  - UPPMAX  
channels:
  - https://conda.anaconda.org/bioconda/
blacklist:
  - 2pg_cartesian-1.0.1-0
  - lts-workflows-sm-scrnaseq-slim-0.3.6-py36_1
  - nbgrader-0.5.5-py_2
  - conda-build-3.18.2-py27_0
  - circos-0.69.8-0
log_dir: /home/jonass/conda_logs
server_log_dir: /home/jonass/conda_logs
delta: true
delta_dir: delta_pkgs

